# Generated by Django 4.1.5 on 2023-02-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=1)),
                ("price", models.PositiveIntegerField(blank=True, default=0)),
                ("cart", models.BooleanField(blank=True, default=True)),
                ("options", models.CharField(max_length=255)),
            ],
        ),
    ]
