# Generated by Django 4.1.5 on 2023-02-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_details", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="price",
        ),
    ]
