# Generated by Django 4.1.5 on 2023-02-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="grade",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("AC", "accept"),
                    ("DE", "delivery"),
                    ("CO", "complete"),
                    ("CA", "cancle"),
                ],
                default="AC",
                max_length=10,
            ),
        ),
    ]
