# Generated by Django 4.1.5 on 2023-02-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_options", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productoption",
            name="contents",
        ),
        migrations.AddField(
            model_name="productoption",
            name="option1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productoption",
            name="option2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productoption",
            name="option3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
