# Generated by Django 4.1.5 on 2023-02-27 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "product_options",
            "0002_remove_productoption_contents_productoption_option1_and_more",
        ),
        ("product_categories", "0001_initial"),
        ("artists", "0001_initial"),
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                ("price", models.PositiveIntegerField(default=0)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("desc", models.TextField(blank=True, max_length=1000, null=True)),
                ("hits", models.PositiveIntegerField(default=0)),
                ("image1", models.CharField(blank=True, max_length=255, null=True)),
                ("image2", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="artists.artist"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_categories.productcategory",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product_options.productoption",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
